### ISSUE TITLE
Add Bert-QA for span QA tasks

### ISSUE THREAD

**Issue by pengshuang** [allenai/allennlp-reading-comprehension#10]
Hi

I have implemented BERT-QA(Bert, Roberta and spanbert) for span QA tasks in Allennlp.
Could I create a new pull request and contribute it to the Allennlp or this project ?

**Comment by matt-gardner** [comment]
Thanks @pengshuang!  @dirkgr has started looking into this; Dirk, what's the state of your work?  @pengshuang, I think at the very least it would definitely be helpful to open a PR here so Dirk can compare what he has done / was planning on with what you have.

**Comment by dirkgr** [comment]
I think I'm pretty close to done, but I'd love to take a look at yours, @pengshuang, to see if I could steal some more ideas?

**Comment by pengshuang** [comment]
Sorry, my hometown is affected by the corona-virus and I do not have enough time to complete my code.
